version: "3.7"

services:
  app:
    build: .
    container_name: printers
    restart: always
    ports:
      - "4000:4000"
    command: "yarn start"

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - app
